env:
  TERM: "xterm-256color"

font:
  size: 13
  bold:
    family: "JetBrainsMono Nerd Font"
    style: "Bold"
  italic:
    family: "JetBrainsMono Nerd Font"
    style: "Italic"
  normal:
    family: "JetBrainsMono Nerd Font"
    style: "Regular"

bell:
  duration: 0

window:
  option_as_alt: "OnlyLeft"

keyboard:
  bindings:
    - key: "Return"
      mods: "Shift"
      chars: "\u001b[13;2u"

shell:
  program: "/bin/zsh"
  args:
    - "-l"
