[env]
TERM="xterm-256color"

[font]
size=13
[font.bold]
family="JetBrainsMono Nerd Font"
style="Bold"
[font.italic]
family="JetBrainsMono Nerd Font"
style="Italic"
[font.normal]
family="JetBrainsMono Nerd Font"
style="Regular"


[bell]
duration=0

[window]
option_as_alt="OnlyLeft"
